export const blogData = [
    {
        id: 1,
        image: "/blog.jpg",
        title: "Bloggle Powerful Blog Builder",
        description: "RuffRuff Table of Contents helps you improve readability, effective search engine optimization, and understanding of user needs (In combination with a heat-map tool). Automatic table of contents generation and display using the headings in the content. It is the only app that can automatically generate a table of contents for products and collections. Please try it. You can check the actual table of contents from in the upper left corner.",
        author: "Vikash Thakur",
        createdAt: "12th Oct, 2024",
    },
    {
        id: 2,
        image: "/blog.jpg",
        title: "Understanding JavaScript Closures",
        description: "JavaScript closures are a fundamental concept that allows functions to have access to their outer scope, even after the outer function has executed. Learn how closures work and how to use them effectively in your code.",
        author: "Aditi Sharma",
        createdAt: "5th Oct, 2024",
    },
    {
        id: 3,
        image: "/blog.jpg",
        title: "An Introduction to React Hooks",
        description: "React Hooks provide a way to use state and other React features without writing a class. This blog explores the most commonly used hooks and their applications.",
        author: "Rohit Verma",
        createdAt: "8th Oct, 2024",
    },
    {
        id: 4,
        image: "/blog.jpg",
        title: "Building REST APIs with Node.js",
        description: "Learn how to build RESTful APIs using Node.js and Express. This blog covers the basic principles of REST and guides you through creating your first API.",
        author: "Priya Singh",
        createdAt: "10th Oct, 2024",
    },
    {
        id: 5,
        image: "/blog.jpg",
        title: "CSS Grid: A Complete Guide",
        description: "CSS Grid is a powerful layout system for CSS. This comprehensive guide will walk you through the basics of CSS Grid and how to use it to create responsive layouts.",
        author: "Rahul Desai",
        createdAt: "15th Oct, 2024",
    },
    {
        id: 6,
        image: "/blog.jpg",
        title: "Understanding Asynchronous JavaScript",
        description: "Asynchronous JavaScript allows for non-blocking code execution. This blog explains callbacks, promises, and async/await to help you understand how to work with asynchronous code effectively.",
        author: "Neha Gupta",
        createdAt: "18th Oct, 2024",
    },
    {
        id: 7,
        image: "/blog.jpg",
        title: "Mastering Git and GitHub",
        description: "Git and GitHub are essential tools for developers. This blog provides an overview of version control with Git and how to collaborate using GitHub.",
        author: "Aman Khan",
        createdAt: "22nd Oct, 2024",
    },
    {
        id: 8,
        image: "/blog.jpg",
        title: "Introduction to TypeScript",
        description: "TypeScript is a superset of JavaScript that adds static typing. This blog covers the basics of TypeScript and how it can help you write better code.",
        author: "Sita Mehta",
        createdAt: "25th Oct, 2024",
    },
    {
        id: 9,
        image: "/blog.jpg",
        title: "Effective Web Performance Optimization",
        description: "Web performance optimization is crucial for a good user experience. This blog discusses techniques to improve website loading speed and performance.",
        author: "Karan Malhotra",
        createdAt: "30th Oct, 2024",
    },
    {
        id: 10,
        image: "/blog.jpg",
        title: "The Future of Artificial Intelligence",
        description: "Artificial intelligence is transforming industries. This blog explores the latest trends in AI and its potential impact on various sectors.",
        author: "Nisha Rao",
        createdAt: "1st Nov, 2024",
    },
];
